DROP TABLE "ADDRESS" CASCADE CONSTRAINTS;
DROP TABLE "AUCTION" CASCADE CONSTRAINTS;
DROP TABLE "CARGO_USER" CASCADE CONSTRAINTS;
DROP TABLE "CARRIER" CASCADE CONSTRAINTS;
DROP TABLE "COMPANY" CASCADE CONSTRAINTS;
DROP TABLE "CONTACT_INFO" CASCADE CONSTRAINTS;
DROP TABLE "FIRM" CASCADE CONSTRAINTS;
DROP TABLE "LOAD" CASCADE CONSTRAINTS;
DROP TABLE "USER_ROLE" CASCADE CONSTRAINTS;

DROP SEQUENCE "ADDRESS_SEQ";
DROP SEQUENCE "AUCTION_SEQ";
DROP SEQUENCE "CARGO_USER_SEQ";
DROP SEQUENCE "CARRIER_SEQ";
DROP SEQUENCE "COMPANY_SEQ";
DROP SEQUENCE "CONTACT_INFO_SEQ";
DROP SEQUENCE "FIRM_SEQ";
DROP SEQUENCE "LOAD_SEQ";
DROP SEQUENCE "USER_ROLE_SEQ";

commit;

QUIT;
